# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: log_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "log_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11log_service.proto\x12\x03log\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto"\x7f\n\x0eSendLogRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x1c\n\x05level\x18\x02 \x01(\x0e\x32\r.log.LogLevel\x12\x0f\n\x07message\x18\x03 \x01(\t\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp"B\n\x0fSendLogResponse\x12\x0e\n\x06log_id\x18\x01 \x01(\t\x12\x1f\n\x06status\x18\x02 \x01(\x0e\x32\x0f.log.SendStatus"\xb1\x01\n\x0eGetLogsRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x1c\n\x05level\x18\x02 \x01(\x0e\x32\r.log.LogLevel\x12(\n\x04\x66rom\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12&\n\x02to\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05limit\x18\x05 \x01(\x05\x12\x0f\n\x07message\x18\x06 \x01(\t"4\n\x0fGetLogsResponse\x12!\n\x04logs\x18\x01 \x03(\x0b\x32\x13.log.SendLogRequest"t\n\x0fGetStatsRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\x12(\n\x04\x66rom\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12&\n\x02to\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp"<\n\rLogLevelCount\x12\x1c\n\x05level\x18\x01 \x01(\x0e\x32\r.log.LogLevel\x12\r\n\x05\x63ount\x18\x02 \x01(\x05"Q\n\x10GetStatsResponse\x12\x12\n\ntotal_logs\x18\x01 \x01(\x05\x12)\n\rlogs_by_level\x18\x03 \x03(\x0b\x32\x12.log.LogLevelCount*D\n\x08LogLevel\x12\x19\n\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x08\n\x04INFO\x10\x01\x12\x08\n\x04WARN\x10\x02\x12\t\n\x05\x45RROR\x10\x03*.\n\nSendStatus\x12\r\n\tSTATUS_OK\x10\x00\x12\x11\n\rSTATUS_FAILED\x10\x01\x32\xf0\x01\n\nLogService\x12I\n\x07SendLog\x12\x13.log.SendLogRequest\x1a\x14.log.SendLogResponse"\x13\x82\xd3\xe4\x93\x02\r"\x08/v1/logs:\x01*\x12\x46\n\x07GetLogs\x12\x13.log.GetLogsRequest\x1a\x14.log.GetLogsResponse"\x10\x82\xd3\xe4\x93\x02\n\x12\x08/v1/logs\x12O\n\x08GetStats\x12\x14.log.GetStatsRequest\x1a\x15.log.GetStatsResponse"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/logs/statsB\x16Z\x14/loggrpc_gen;loggrpcb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "log_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\024/loggrpc_gen;loggrpc"
    _globals["_LOGSERVICE"].methods_by_name["SendLog"]._loaded_options = None
    _globals["_LOGSERVICE"].methods_by_name[
        "SendLog"
    ]._serialized_options = b'\202\323\344\223\002\r"\010/v1/logs:\001*'
    _globals["_LOGSERVICE"].methods_by_name["GetLogs"]._loaded_options = None
    _globals["_LOGSERVICE"].methods_by_name[
        "GetLogs"
    ]._serialized_options = b"\202\323\344\223\002\n\022\010/v1/logs"
    _globals["_LOGSERVICE"].methods_by_name["GetStats"]._loaded_options = None
    _globals["_LOGSERVICE"].methods_by_name[
        "GetStats"
    ]._serialized_options = b"\202\323\344\223\002\020\022\016/v1/logs/stats"
    _globals["_LOGLEVEL"]._serialized_start = 783
    _globals["_LOGLEVEL"]._serialized_end = 851
    _globals["_SENDSTATUS"]._serialized_start = 853
    _globals["_SENDSTATUS"]._serialized_end = 899
    _globals["_SENDLOGREQUEST"]._serialized_start = 89
    _globals["_SENDLOGREQUEST"]._serialized_end = 216
    _globals["_SENDLOGRESPONSE"]._serialized_start = 218
    _globals["_SENDLOGRESPONSE"]._serialized_end = 284
    _globals["_GETLOGSREQUEST"]._serialized_start = 287
    _globals["_GETLOGSREQUEST"]._serialized_end = 464
    _globals["_GETLOGSRESPONSE"]._serialized_start = 466
    _globals["_GETLOGSRESPONSE"]._serialized_end = 518
    _globals["_GETSTATSREQUEST"]._serialized_start = 520
    _globals["_GETSTATSREQUEST"]._serialized_end = 636
    _globals["_LOGLEVELCOUNT"]._serialized_start = 638
    _globals["_LOGLEVELCOUNT"]._serialized_end = 698
    _globals["_GETSTATSRESPONSE"]._serialized_start = 700
    _globals["_GETSTATSRESPONSE"]._serialized_end = 781
    _globals["_LOGSERVICE"]._serialized_start = 902
    _globals["_LOGSERVICE"]._serialized_end = 1142
# @@protoc_insertion_point(module_scope)
