# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

# import log_service_pb2 as log__service__pb2
from . import log_service_pb2 as log__service__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in log_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class LogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendLog = channel.unary_unary(
            "/log.LogService/SendLog",
            request_serializer=log__service__pb2.SendLogRequest.SerializeToString,
            response_deserializer=log__service__pb2.SendLogResponse.FromString,
            _registered_method=True,
        )
        self.GetLogs = channel.unary_unary(
            "/log.LogService/GetLogs",
            request_serializer=log__service__pb2.GetLogsRequest.SerializeToString,
            response_deserializer=log__service__pb2.GetLogsResponse.FromString,
            _registered_method=True,
        )
        self.GetStats = channel.unary_unary(
            "/log.LogService/GetStats",
            request_serializer=log__service__pb2.GetStatsRequest.SerializeToString,
            response_deserializer=log__service__pb2.GetStatsResponse.FromString,
            _registered_method=True,
        )


class LogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_LogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SendLog": grpc.unary_unary_rpc_method_handler(
            servicer.SendLog,
            request_deserializer=log__service__pb2.SendLogRequest.FromString,
            response_serializer=log__service__pb2.SendLogResponse.SerializeToString,
        ),
        "GetLogs": grpc.unary_unary_rpc_method_handler(
            servicer.GetLogs,
            request_deserializer=log__service__pb2.GetLogsRequest.FromString,
            response_serializer=log__service__pb2.GetLogsResponse.SerializeToString,
        ),
        "GetStats": grpc.unary_unary_rpc_method_handler(
            servicer.GetStats,
            request_deserializer=log__service__pb2.GetStatsRequest.FromString,
            response_serializer=log__service__pb2.GetStatsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "log.LogService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("log.LogService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class LogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendLog(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/log.LogService/SendLog",
            log__service__pb2.SendLogRequest.SerializeToString,
            log__service__pb2.SendLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetLogs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/log.LogService/GetLogs",
            log__service__pb2.GetLogsRequest.SerializeToString,
            log__service__pb2.GetLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetStats(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/log.LogService/GetStats",
            log__service__pb2.GetStatsRequest.SerializeToString,
            log__service__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
